version: '3.4'

services:
  app-api-dev:
    container_name: dev
    image: alexfariakof/infnet-24e1_3-dev-img
    build:
      context: .
      dockerfile: LiteStreaming.WebApi/Dockerfile.Development
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+5146;https://+7204;
    ports:       
       - 5146:5146
       - 7204:7204
