version: '3.4'

services:
  app-sts-prod:
    container_name: sts-prod
    image: alexfariakof/app-sts-server-prod-img
    build:
      context: ..
      dockerfile: LiteStreaming.STS/Dockerfile.Production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80;https://+:443
    ports:
       - 80:80
       - 443:443


