version: '3.4'
services:
  app-admin-dev:
    container_name: admin-dev
    image: alexfariakof/administrative-app-dev-img
    build:
      context: ..
      dockerfile: LiteStreaming.AdministrativeApp/Dockerfile.Development
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+5171;https://+7230;
    ports:
      - 7230:443
      - 5171:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro