name: Deploy STS Server
on:
  push:
    tags:
      - sts-v*.*.*

permissions:
    contents: read 

jobs:
  trigger_build:
    name: Triggered STS  Dev
    uses: alexfariakof/prj-sistemas-web-.net-infnet/.github/workflows/STS_Server_build_.yml@main
    secrets: inherit  
   
  deploy:
    needs: trigger_build
    name:  Publish STS Server in AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        env:
          DOCKER_CLI_AGGREGATE: 1  
        run: |          
            docker-compose -f ./LiteStreaming.STS/docker-compose.dev.yml build
        continue-on-error: false

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_CLI_AGGREGATE: 1  
        run: |
            docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}    
            docker push alexfariakof/app-sts-server-dev-img
        continue-on-error: false
        
      - name: Execute SSH Commands into EC2 
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |            
            ./scripts/sts-server.dev.sh

